---
- hosts: local

  pre_tasks:
    - name: add NFS share to j2 tempalte directly since updating via the j2 template isn't working
      lineinfile:
        path: ~/.ansible/roles/geerlingguy.nfs/templates/exports.j2
        line: /data/nfsroot/posters *(rw,sync,no_root_squash)

    - name: Update docroot defaults for Apache
      replace:
        path: ~/.ansible/roles/geerlingguy.apache/defaults/main.yml
        regexp: '(\s+)documentroot: "/var/www/html"(\s+.*)?$'
        replace: '\1documentroot: "/data/nfsroot/posters"\2'
        backup: yes

    - name: Create folder for posters share
      file:
        path: /data/nfsroot/posters
        state: directory

  roles:
    - { role: geerlingguy.apache }
    - { role: geerlingguy.nfs }

  post_tasks:
    - name: Wait until the folder /data/nfsroot/posters/ is present before continuing
      wait_for:
        path: /data/nfsroot/posters/

    - name: Restart service nfs, in all cases
      service:
        name: nfs
        state: restarted

    - name: Change the SELinux security context
      command: chcon -R -t httpd_sys_content_t /data/nfsroot/posters/

    - name: verify that an NFS share exists
      command: showmount -e localhost

    - name: Create mount point for local NFS share to test it
      file:
        path: /mnt/nfstest
        state: directory

    - name: set mountpoints
      mount: name=/mnt/nfstest src=localhost:/data/nfsroot/posters fstype=nfs opts=rw dump=0 passno=0 state=mounted

    - name: download a sample image file to the NFS share
      command: chdir=/mnt/nfstest wget https://img-aws.ehowcdn.com/240x360p/photos.demandstudios.com/getty/article/163/20/200329275-001_XS.jpg

    - name: fetch that sample image file over http
      command: chdir=/mnt/nfstest wget http://localhost/200329275-001_XS.jpg
